version: 0.0
os: ubuntu
files:
  - source: /
    destination: /app #where to store the artifacts
hooks:
  ApplicationStart:
    - location: /scripts/start.sh #start script for the website
      timeout: 300
      runas: root
